// This file is generated by GoAdmin CLI adm.
package admin_datamodel

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "courses" => http://localhost:9033/admin/info/courses
// "course_reviews_courses" => http://localhost:9033/admin/info/course_reviews_courses
// "course_reviews" => http://localhost:9033/admin/info/course_reviews
// "course_tags_courses" => http://localhost:9033/admin/info/course_tags_courses
// "course_tags" => http://localhost:9033/admin/info/course_tags
// "course_sections" => http://localhost:9033/admin/info/course_sections
// "course_galleries" => http://localhost:9033/admin/info/course_galleries
// "course_lessons" => http://localhost:9033/admin/info/course_lessons
// "users" => http://localhost:9033/admin/info/users
//
// example end
var Generators = map[string]table.Generator{

	"courses": GetCoursesTable,
	// "course_reviews_courses": GetCourseReviewsCoursesTable,
	// "course_reviews":         GetCourseReviewsTable,
	"course_tags_courses": GetCourseTagsCoursesTable,
	"course_tags":         GetCourseTagsTable,
	"course_sections":     GetCourseSectionsTable,
	// "course_galleries":       GetCourseGalleriesTable,
	// "course_lessons":         GetCourseLessonsTable,
	// "users":                  GetUsersTable,

	// generators end
}
