// This file is generated by GoAdmin CLI adm.
package admin_datamodel

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

var Generators = map[string]table.Generator{
	"courses":             GetCoursesTable,
	"course_tags_courses": GetCourseTagsCoursesTable,
	"course_tags":         GetCourseTagsTable,
	"course_sections":     GetCourseSectionsTable,
	"course_galleries":    GetCourseGalleriesTable,
	"course_lessons":         GetCourseLessonsTable,

	// generators end
}
