version: '1.0'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: code_with_azri
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - local_network

  CWADev:
    image: code-with-azri-dev
    build:
      context: .
      args:
        - ENV_FILE=dev.env
        - FIREBASE_PATH=code-with-azri-firebase-adminsdk-vf6lc-bd1eeda135.json
    ports:
      - "8080:8080"
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

 