version: '1.0'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: code_with_azri
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - local_network

  code-with-azri-local:
    image: code-with-azri-local
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

 