// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "CodeWithAzri/internal/app/module/user/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: e
func (_m *UserRepository) Create(e entity.User) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.User) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - e entity.User
func (_e *UserRepository_Expecter) Create(e interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", e)}
}

func (_c *UserRepository_Create_Call) Run(run func(e entity.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.User))
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(_a0 error) *UserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(entity.User) error) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *UserRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *UserRepository_Expecter) Delete(id interface{}) *UserRepository_Delete_Call {
	return &UserRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *UserRepository_Delete_Call) Run(run func(id string)) *UserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserRepository_Delete_Call) Return(_a0 error) *UserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_Delete_Call) RunAndReturn(run func(string) error) *UserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ReadMany provides a mock function with given fields: limit, offset
func (_m *UserRepository) ReadMany(limit int, offset int) ([]entity.User, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ReadMany")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]entity.User, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []entity.User); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_ReadMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadMany'
type UserRepository_ReadMany_Call struct {
	*mock.Call
}

// ReadMany is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *UserRepository_Expecter) ReadMany(limit interface{}, offset interface{}) *UserRepository_ReadMany_Call {
	return &UserRepository_ReadMany_Call{Call: _e.mock.On("ReadMany", limit, offset)}
}

func (_c *UserRepository_ReadMany_Call) Run(run func(limit int, offset int)) *UserRepository_ReadMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *UserRepository_ReadMany_Call) Return(_a0 []entity.User, _a1 error) *UserRepository_ReadMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_ReadMany_Call) RunAndReturn(run func(int, int) ([]entity.User, error)) *UserRepository_ReadMany_Call {
	_c.Call.Return(run)
	return _c
}

// ReadOne provides a mock function with given fields: id
func (_m *UserRepository) ReadOne(id string) (entity.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ReadOne")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entity.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entity.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_ReadOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadOne'
type UserRepository_ReadOne_Call struct {
	*mock.Call
}

// ReadOne is a helper method to define mock.On call
//   - id string
func (_e *UserRepository_Expecter) ReadOne(id interface{}) *UserRepository_ReadOne_Call {
	return &UserRepository_ReadOne_Call{Call: _e.mock.On("ReadOne", id)}
}

func (_c *UserRepository_ReadOne_Call) Run(run func(id string)) *UserRepository_ReadOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserRepository_ReadOne_Call) Return(_a0 entity.User, _a1 error) *UserRepository_ReadOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_ReadOne_Call) RunAndReturn(run func(string) (entity.User, error)) *UserRepository_ReadOne_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, e
func (_m *UserRepository) Update(id string, e entity.User) error {
	ret := _m.Called(id, e)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, entity.User) error); ok {
		r0 = rf(id, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id string
//   - e entity.User
func (_e *UserRepository_Expecter) Update(id interface{}, e interface{}) *UserRepository_Update_Call {
	return &UserRepository_Update_Call{Call: _e.mock.On("Update", id, e)}
}

func (_c *UserRepository_Update_Call) Run(run func(id string, e entity.User)) *UserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(entity.User))
	})
	return _c
}

func (_c *UserRepository_Update_Call) Return(_a0 error) *UserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_Update_Call) RunAndReturn(run func(string, entity.User) error) *UserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
